# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
