# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_form', '0003_auto_20171018_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
